language: node_js
node_js:
  - "node"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

before_script:
  - npm i -g vue-cli

cache:
  directories:
    - "node_modules"

script:
  - npm run build

deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email: false
  slack: cbrecode:Sj3O9DRJNMCBit4SGea5WK4I